apiVersion: 1

datasources:
  # PROMETHEUS
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST
      # Связка с Tempo для перехода Metrics -> Traces
      exemplarTraceIdDestinations:
        - name: trace_id
          datasourceUid: tempo

  # LOKI
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    jsonData:
      # Связка с Tempo для перехода Logs -> Traces
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "traceID=(\\w+)"
          name: TraceID
          url: "$${__value.raw}"

  # TEMPO
  - name: Tempo
    uid: tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      httpMethod: GET
      grpcAddress: "tempo:9095"
      insecure: true
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: 'Prometheus'
      lokiSearch:
        datasourceUid: 'Loki'
      tracesToLogsV2:
        datasourceUid: 'Loki'
        groupSigularBy: ['cluster', 'namespace', 'pod']
